name: bam_analysis
description: Lint and dcm rules for Dart and Flutter used internally at BAM.
homepage: https://github.com/bamlab/bam_analysis
repository: https://github.com/bamlab/bam_analysis
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^6.0.0
