name: bam_analysis
description: We want to share our appreciation of what a good analysis configuration can do for your project. This package is a collection of our best practices and analysis rules that we use in our projects at BAM.
homepage: https://github.com/bamlab/bam_analysis
repository: https://github.com/bamlab/bam_analysis
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
